// Generated by dts-bundle v0.7.3

export class Filter {
    constructor(options: IFilterOptions);
    bind: (filters: IFacet[]) => void;
}

export interface IFilterOptions {
    containerElement: HTMLElement | null;
    onFilterChange: IFilterActionDelegate;
    onAllFilterRemove: IAllFilterRemoveDelegate;
}

export interface IFacet {
    id: string;
    name: string;
    type: DataType;
    facetValues: IFacetValue[];
    facetRange: IFacetRange;
}

export type IAllFilterRemoveDelegate = () => void;

export type IFilterActionDelegate = (key: string, value: string, action: FilterActionType) => void;

export enum DataType {
    String = "String",
    Date = "Date",
    Number = "Number",
    Boolean = "Boolean",
    Collection = "Collection",
}

export interface IFacetRange {
    min: string;
    max: string;
    minIncluded: boolean;
    maxIncluded: boolean;
}

export interface IFacetValue {
    label: string;
    count: number;
    selected: boolean;
}

export enum FilterActionType {
    Add = "Add",
    Minus = "Minus",
}

